### ISSUE TITLE
skins missing

### ISSUE THREAD

**Issue by esaruoho** [cmicali/ztracker#1]
hi @cmicali  it seems that at least these skins are missing:
- [x] blue-c64
- [x] reaktor
- [x] tekstyle
- [x] x.seed
- [x] xt-g01

d'you have plans of adding them? I tried to find someone to create a macOS -compilable version of ztracker, but so far haven't had much luck. Anyway, the skins are here: https://github.com/esaruoho/ztracker_mac/tree/master/skins

I've also mirrored some of the ztracker-sourceforge-net screenshots, for the sake of retaining zTracker's legacy.

**Comment by cmicali** [comment]
Hey Esa!

Happy to make you a comitter on the main ztracker repo - would be fantastic to get it up to date with latest bits and also merge osx support there. Interested?

**Comment by esaruoho** [comment]
@cmicali hi, I could add some bits and bobs in there. I've also reached out to the developer of ZT2IT and he has expressed some interest in pushing his ZT to IT -converter code to Github. Maybe he could be persuaded to work on the official main zTracker repo too.

There's also that ztrackerprime guy, I'll ask him about his interest.

**Comment by cmicali** [comment]
Just added, happy to add more if there is interest

**Comment by esaruoho** [comment]
Ok, let's see about them skins.

**Comment by esaruoho** [comment]
created PR #3 - merged it in.

**Comment by esaruoho** [comment]
created PR #4 and merged it in. this issue can now be closed..
